version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "35432:5432"

  web:
    build: ./server
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db 
    depends_on:
      - db 
    ports:
      - "3000:3000"


