version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "35432:5432"

  web:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - db 
    ports:
      - "3000:3000"


